### ISSUE TITLE
Example needed: Login and Observe

### ISSUE THREAD

**Issue by fnogatz** [sonnym/fics#2]
Hi,
unfortunately I can't get the observe function working. Could you please provide an example how one would use `fics` to first authenticate and then observe a game?
I had the impression that some messages from FICS must have changed, as your tests work with mocked server replies.

**Comment by sonnym** [comment]
I just added an explicit example of logging in as a guest and observing a game: https://github.com/sonnym/fics/blob/2643c5094514cfe3f405ac9ff110c13310eacca1/examples/login_and_observe.js

**Comment by fnogatz** [comment]
Thank you very much for coming back to this. Seems like I still have to learn a lot about Promises :) Thanks for your example!
